version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_async:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    env_file:
      - .env.docker
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  app:
    build: .
    ports:
      - "8080:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - minio

volumes:
  postgres_data_async:
  minio_data:
